### ISSUE TITLE
vb-content with display:flex?

### ISSUE THREAD

**Issue by Tech-Nomad** [DominikSerafin/vuebar#81] opened 2019-06-09 00:53 UTC
Hi, 
thank you for this great library! 
Though one problem I have encountered using it in my project is that it doesn't work with .vb-content set to display:flex - you get the usual scrollbar to see. 
(I need the flexbox functionality for stretching the container content to the height of the window if the summed height of the elements is less than the window height -  flexbox sets perfectly the right proportions of the elements within container.)

Any ideas?

**Comment by Tech-Nomad** [comment] 2019-06-09 00:58
Here is one screenshot with display: flex
![Screenshot 2019-06-09 at 02 57 17](https://user-images.githubusercontent.com/18289087/59153758-7a9c4300-8a62-11e9-9ebe-9606c190edad.png)

**Comment by Tech-Nomad** [comment] 2019-06-09 00:59
And here with display: block
![Screenshot 2019-06-09 at 02 56 33](https://user-images.githubusercontent.com/18289087/59153764-999ad500-8a62-11e9-9bea-863bc4e52da5.png)

**Comment by Tech-Nomad** [comment] 2019-06-09 01:17
Sorry, I was wrong. It does actually show the Vuebar and the original one is hidden. But the container isn't scrollable even you drag the scrollbar manually.

**Comment by Tech-Nomad** [comment] 2019-06-09 01:18
![Screenshot 2019-06-09 at 03 15 22](https://user-images.githubusercontent.com/18289087/59153878-2cd50a00-8a65-11e9-85af-67215389b8f5.png)

**Comment by DominikSerafin** [comment] 2019-08-30 13:47
For now, I'm going to close this as this seems like issue unrelated to intended behavior of Vuebar.

I could look into it but I'll need a minimal reproduction first. Feel free to reopen with that provided. Thanks!

**Closed by DominikSerafin** 2019-08-30 13:47 UTC
