### ISSUE TITLE
Appearing browser bar in IE11 after shown tooltip

### ISSUE THREAD

**Issue by alorenc** [DominikSerafin/vuebar#80] opened 2019-06-05 08:08 UTC
Hi,

I have a problem with the Bootstrap Tooltip components, only in IE11.
After displaying the "tooltip" on any item of the scrolling object. The browser slider briefly appears, and then the vuabar script will correct it. Unfortunately, it does not look very nice.

![vuebar_ie11_tooltip](https://user-images.githubusercontent.com/22193695/58940211-36b2f080-8779-11e9-943c-70d01403fcd6.gif)

How to fix it?

I am using the Vue Bootstrap component if it matters.

**Comment by DominikSerafin** [comment] 2019-08-30 13:44
It seems like overflow issue with container other than Vuebar. My guess is that tooltip component goes outside of that container bounds for a short amount of time. So it looks like this issue is unrelated to the Vuebar itself. 

For now I'm closing this. If it's indeed problem with Vuebar - please provide minimal reproduction and I'll reopen it. Thanks!

**Closed by DominikSerafin** 2019-08-30 13:44 UTC
